# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojosecrets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alias',
        ),
    ]
